### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by XavierBrassoud** [SavchukSergey/SwfLib#3]
Hi,

Thank's for this nice library.

This project has no license, so theoretically / strictly legally nobody is allowed to use it, except to study the code and fork it here on github (but then you can't do anything with the fork). Even contributors can't use the library since they all share exclusive copyright for the code and should always ask permission from all other contributors before using the code in any way.

More details: https://choosealicense.com/no-license/

Could you add a licence please?

Thank's in advance :)

**Comment by SavchukSergey** [comment]
Thank you
Just added MIT licence
