### ISSUE TITLE
Upgrading to .NET Standard planned ?

### ISSUE THREAD

**Issue by XavierBrassoud** [SavchukSergey/SwfLib#6]
Hi,

Is it planned to [upgrade](https://www.danielcrabtree.com/blog/314/upgrading-to-net-core-and-net-standard-made-easy) this lib to support .NET Core ?

Thank's in advance :)

**Comment by SavchukSergey** [comment]
There is System.Drawing dependency.

Not sure what's the best way to mitigate it. Either reference some alternative package like CoreCompat or use conditional compilation to skip some functionality for .net core

**Comment by XavierBrassoud** [comment]
Ok thank's for your reply. If I find an alternative for this, I share it.

**Comment by XavierBrassoud** [comment]
Hi,

Thanks for your changes, that is really great. 
I open this issue again to improve the porting of your library.

In [SwfLib.csproj](https://github.com/SavchukSergey/SwfLib/commit/c12d2953981954ae77f083a2865eadba1310642b#diff-ef41f6e33bee5d60dcf513ec7050c45a), you specified "netcoreapp2.0":
```xml
<TargetFrameworks>net461;netcoreapp2.0</TargetFrameworks> 
```

<br/>

It's really much better to put "**netstandard2.0**" instead of "netcoreapp2.0":
```xml
<TargetFrameworks>net461;netstandard2.0</TargetFrameworks>
```

<br/>
<br/>

The .NET Standard 2.0 integrates the .NET Core 2.0 (and much more), so you do not need to modify the others .csproj of your solution (like your tests, which run both on .NET Framework 4.6.1 and .NET Core 2.0).

![](https://cdiese.fr/wp-content/uploads/netstandard/dotnet-tomorrow.png)

<br/>

It's possible to fix this and upload a new NuGet package ?

Promised, I will not bother you more with this portage ;)

Thank's in advance!

**Comment by IS4Code** [comment]
@SavchukSergey Could you also please specify `netstandard2.0` alongside `netstandard2.1` as the target framework? Considering .NET Framework 4.6 is supported, there shouldn't be any features that prevent .NET Standard 2.0 from working as well.
