### ISSUE TITLE
How to replace defineBitsLossless2Tag.ZlibBitmapData 

### ISSUE THREAD

**Issue by barisyild** [SavchukSergey/SwfLib#8]
`DefineBitsLossless2Tag defineBitsLossless2Tag = (DefineBitsLossless2Tag)tag;

FileStream fileStream = File.OpenRead(startupPath + "\\library\\1.png");
Image image = Image.FromStream(fileStream);
Bitmap bitmap = new Bitmap(image);
ImageConverter converter = new ImageConverter();
defineBitsLossless2Tag.ZlibBitmapData = (byte[])converter.ConvertTo(bitmap, typeof(byte[]));`

ZlibBitmapData replacing not working.

**Comment by SavchukSergey** [comment]
Hi
According to SWF specification, ZlibBitmapData contains compressed raw pixel data.
And exact format depends on whether image is built using color palette or not.
Just added basic support for regular images (without palette)

See new methods BuildBitmap and SetImage

Should be available in SwfLib 1.0.3 (it is now being indexed by nuget.org)

**Comment by SavchukSergey** [comment]
Let me know if it works for you

**Comment by barisyild** [comment]
DefineBitsLossless2Tag defineBitsLossless2Tag = (DefineBitsLossless2Tag)tag;
FileStream fileStream = File.OpenRead(startupPath + "\\q7d2i6jg\\1.png");
Image image = Image.FromStream(fileStream);
Bitmap bitmap = new Bitmap(image);
defineBitsLossless2Tag.SetImage(bitmap);
defineBitsLossless2Tag.BuildBitmap();

Not working :(

![image](https://user-images.githubusercontent.com/25794892/47679378-32b46400-dbd5-11e8-89a0-30498e7a26b6.png)

**Comment by barisyild** [comment]
DefineBitsLossless2Tag defineBitsLossless2Tag = (DefineBitsLossless2Tag)tag;
FileStream fileStream = File.OpenRead(startupPath + "\\q7d2i6jg\\1.png");
Image image = Image.FromStream(fileStream);
Bitmap bitmap = defineBitsLossless2Tag.BuildBitmap();
Graphics gr = default(Graphics);
gr = Graphics.FromImage(image);
Rectangle rect = new Rectangle(50, 50, image.Width, image.Height); // where to draw
gr.DrawImage(bitmap, rect);
defineBitsLossless2Tag.SetImage(bitmap);

Not Working :(

**Comment by barisyild** [comment]
Fullcode

FileStream swfStream = File.OpenRead(startupPath + "/library_original.swf");
SwfLib.SwfFile swfFile = SwfFile.ReadFrom(swfStream);
IList<SwfTagBase> tags = swfFile.Tags;
foreach(object tag in tags)
{
	Console.WriteLine(tag.ToString());
	if(tag.ToString() == "SwfLib.Tags.BitmapTags.DefineBitsLossless2Tag")
	{
		DefineBitsLossless2Tag defineBitsLossless2Tag = (DefineBitsLossless2Tag)tag;
		FileStream fileStream = File.OpenRead(startupPath + "\\library\\1.png");
		Image image = Image.FromStream(fileStream);
		Bitmap bitmap = defineBitsLossless2Tag.BuildBitmap();
		Graphics gr = Graphics.FromImage(image);
		Rectangle rect = new Rectangle(0, 0, image.Width, image.Height); // where to draw
		gr.DrawImage(bitmap, rect);
		defineBitsLossless2Tag.SetImage(bitmap);
	}
}
 using (var target = File.Open("library.swf", FileMode.Create, FileAccess.ReadWrite))
{
	swfFile.WriteTo(target);
	target.Flush();
}

**Comment by SavchukSergey** [comment]
Hi
Your code contains several issues
1. file path to image is not properly escaped. You need either @ character before "\library\1.png" string or double \ characters
2. ```IList<SwfTagBase>``` doesn't convert to ```IList```
3. ```BuildBitmap()``` creates a bitmap from data that are already set to tag. You are updating Image object that is read from png file. I suppose you want to replace tag data instead.
4. Proper way to check tag is using "is" keyword. You can even use new c# feature to assign an alias ```if (tag is SwfLib.Tags.BitmapTags.DefineBitsLossless2Tag defineBitsLossless2Tag)```

Should be something like below
```c#
var swfStream = File.OpenRead(startupPath + "/library_original.swf");
var swfFile = SwfFile.ReadFrom(swfStream);
foreach (var tag in swfFile.Tags) {
    if (tag is SwfLib.Tags.BitmapTags.DefineBitsLossless2Tag defineBitsLossless2Tag) {
        var fileStream = File.OpenRead(startupPath + @"\library\1.png");
        var image = Image.FromStream(fileStream);
        
        var bitmap = defineBitsLossless2Tag.BuildBitmap();
        var gr = Graphics.FromImage(bitmap);
        var rect = new Rectangle(0, 0, bitmap.Width, bitmap.Height); // where to draw
        gr.DrawImage(image, rect);

        defineBitsLossless2Tag.SetImage(bitmap);
    }
}
using (var target = File.Open("library.swf", FileMode.Create, FileAccess.ReadWrite)) {
    swfFile.WriteTo(target);
    target.Flush();
}
```

**Comment by barisyild** [comment]
Example works but image has pixel problem.

Original:
![image](https://user-images.githubusercontent.com/25794892/47740169-37862000-dc88-11e8-9dea-09b6737b350c.png)

SetImage:
![image](https://user-images.githubusercontent.com/25794892/47740201-4c62b380-dc88-11e8-88fa-1f4d88ecd5fa.png)

**Comment by barisyild** [comment]
defineBitsLossless2Tag.SetImage not working correctly :(
The edges of all images has pixelated :(

![image](https://user-images.githubusercontent.com/25794892/47829766-1d3c6700-dd9a-11e8-8a8c-5978c7749dea.png)

**Comment by barisyild** [comment]
help?

**Comment by SavchukSergey** [comment]
Sorry, I won't be able to manage that this week.
Will try to fix that on Monday.

**Comment by barisyild** [comment]
can you fix it today?

**Comment by SavchukSergey** [comment]
Just uploaded potential fix
Version 1.0.4
Please check

**Comment by barisyild** [comment]
It worked, thank you.
